---
title: "Webscraping2"
output: pdf_document
---

```{r setup}
library(tidyverse)
library(rvest)
```

## Kode fra dag 7

Men skreddersydd til ssb-casen vår.

```{r}
ssb <- download_html(
  url = "https://www.ssb.no/",
  file = "../Data/SSB.html"
)

# kategorier <- ["/arbeid-og-lonn"]

links <- read_html("../Data/SSB.html") %>%
  html_nodes('a[class="ssb-link with-icon"]') %>% # Vet ikke om jeg trenger denne
  # html_elements("a") %>%
  html_attr("href") %>%
  # str_extract("") #%>%
  # na.omit() %>% 
  str_c("https://ssb.no", .)

links
# FUNKER!
```

Laste ned alle nettsidene:

```{r}
# Nå trenger vi en for-loop som laster ned alle 23 linkene som html-fil
```

Iterere gjennom alle 23 html-filene lasted ned lokalt for å finne underlinkene:

```{r}
# Step 2: Download all the webpages from the links you just made
linkstopic <- str_remove(links, "https://ssb.no") 

for(i in 1:length(links)) { # For all the links... 
   
  download.file(links[[i]], 
                destfile = str_c("../Data/links/", linkstopic[i], ".html")) 
  # Download one html-file after another into the folder 
   
    Sys.sleep(2) 
  # Setting a timer of two seconds each time we download a webpage.  
}
```

```{r}
# Step 3: Loop over every link and extract the text using the same procedure as shown before
info <- list()  
# Make a list-object where you can put the output from the loop 
for (i in 1:length(links)) { 
# For each i in every element from place number one to the last place in links (given by length(links)) 
   
  page <- read_html(links[[i]])  
  # Read the html-page for each i 
   
  page <- page %>% # Use this page 
    html_elements("p") %>% # And fetch the paragraph elements 
    html_text() # Then extract the text from these elements 
   
  info[[i]] <- page  
  # Place the text for each link into its respective place in the info-object
   
}
```

